version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: smart_inventory_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SmartInventoryOrderManagementSystem
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    container_name: smart_inventory_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: smart_inventory_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    container_name: smart_inventory_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  mysql-data:
  redis-data:
  zookeeper-data:
  kafka-data:
